## Analytic Methods

As methods-y people, we often want to get into a lot of detail here (I will speak for myself at least!). But this is another moment where you really need to consider your audience and overarching goals carefully. You are probably doing a number of things in the paper that merit explanation in the methods section, but the ones you highlight in this section should fit the following criteria :

1. **What is the most important thing you're trying to do with your paper, and which methods are most crucial to understanding that** This is another way of saying that you should focus on the most  model or set of models in the paper that are most important to understanding your results and advancing your overall agenda with the paper.  You may have sub-analyses that provide extra detail but don't need to be outlined in depth in the main part of the manuscript. In the worst case, you can always refer the reader to a supplement containing this information. 
	1. **Which methods are important enough to describe is a function of your audience.** Think about what kind of paper this is and who you expect to read it; that will dictate what goes in this section. The more generic the audience is, the more likely you will have a lot of the methods in a supplement, whereas for a more specialist audience - either a sub-field in epidemiology or a more methodological journal - you will probably go into more depth.
2. **How does what you're doing methodologically relate to the major questions of your analysis?** Remember that the methods section exists to give the reader the ability to understand evaluate the results you are presenting to them.*So, if it's not going to be in the results in some way, it shouldn't be in the methods.*
